version: '3.8'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:${DASHBOARD_VERSION:-v3.1.2}
    ports:
      - 3000:3000
    networks:
      - tyk
    volumes:
      - ./deployments/tyk/volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
      - ./deployments/tyk/volumes/tyk-dashboard/private-key.pem:/opt/tyk-dashboard/private-key.pem
      - ./deployments/tyk/volumes/tyk-dashboard/catalogue.html:/opt/tyk-dashboard/portal/templates/catalogue.html
      - ./deployments/tyk/volumes/tyk-dashboard/navigation.html:/opt/tyk-dashboard/portal/templates/navigation.html
      - ./deployments/tyk/volumes/tyk-dashboard/audit.log:/opt/tyk-dashboard/audit.log
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE:?Dashboard licence missing from Docker environment file .env. Review The Getting Started steps in README.md.}
      - TYK_LOGLEVEL=${DASHBOARD_LOGLEVEL:-info}
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
    env_file:
    - .env
    depends_on:
      - tyk-redis
      - tyk-mongo
  tyk-gateway:
    image: tykio/tyk-gateway:${GATEWAY_VERSION:-v3.1.2}
    ports:
      - 8080:8080
      - 8086:8086
    networks:
      tyk:
        aliases:
          - tyk-custom-domain.com
    environment:
      - TYK_LOGLEVEL=${GATEWAY_LOGLEVEL:-info}
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
      - TYK_GW_TRACER_ENABLED=${TRACING_ENABLED:-false}
      - TYK_GW_SECRET=28d220fd77974a4facfb07dc1e49c2aa
      - TYK_GW_NODESECRET=352d20ee67be67f6340b4c0605b044b7
      - TYK_GW_POLICIES_POLICYSOURCE=service
      - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=http://tyk-dashboard:3000
      - TYK_GW_POLICIES_POLICYRECORDNAME=tyk_policies
      - TYK_GW_POLICIES_ALLOWEXPLICITPOLICYID=true
      - TYK_GW_USEDBAPPCONFIGS=true
      - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=http://tyk-dashboard:3000
      - TYK_GW_DISABLEPORTSWHITELIST=true
      - TYK_GW_STORAGE_HOST=tyk-redis
      - TYK_GW_ENABLEANALYTICS=true
      - TYK_GW_ANALYTICSCONFIG_TYPE=mongo
      - TYK_GW_ANALYTICSCONFIG_NORMALISEURLS_ENABLED=true
      - TYK_GW_ANALYTICSCONFIG_NORMALISEURLS_NORMALISEUUIDS=true
      - TYK_GW_ANALYTICSCONFIG_NORMALISEURLS_NORMALISENUMBERS=true
      - TYK_GW_HEALTHCHECK_ENABLEHEALTHCHECKS=false
      - TYK_GW_OPTIMISATIONSUSEASYNCSESSIONWRITE=true
      - TYK_GW_HASHKEYS=true
      - TYK_GW_HASHKEYFUNCTION=murmur64
      - TYK_GW_USEREDISLOG=true
      - TYK_GW_ENFORCEORGDATAAGE=true
      - TYK_GW_ENFORCEORGQUOTAS=true
      - TYK_GW_ALLOWINSECURECONFIGS=false
      - TYK_GW_PUBLICKEYPATH=certs/public-key.pem
      - TYK_GW_ALLOWREMOTECONFIG=true
      - TYK_GW_BUNDLEBASEURL=http://http-server/
      - TYK_GW_TRACING_NAME=zipkin
      - TYK_GW_TRACING_OPTIONS_REPORTER_URL=http://zipkin:9411/api/v2/spans
      - TYK_GW_ENABLEHASHEDKEYSLISTING=true
      - TYK_GW_UPTIMETESTS_CONFIG_ENABLEUPTIMEANALYTICS=true
      - TYK_GW_ENABLECUSTOMDOMAINS=true
      - TYK_GW_ENABLEJSVM=true
      - TYK_GW_COPROCESSOPTIONS_ENABLECOPROCESS=true
      - TYK_GW_STATSDCONNECTIONSTRING=graphite:8125
      - TYK_GW_SECRETS=target_url:httpbin.org,listen_path:/secret-path/,header:secret-header-value
    env_file:
      - .env
    volumes:
      - ./deployments/tyk/volumes/tyk-gateway/certs:/opt/tyk-gateway/certs
      - ./deployments/tyk/volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
      - ./deployments/tyk/volumes/tyk-gateway/plugins:/opt/tyk-gateway/plugins
      - ./deployments/tyk/volumes/tyk-gateway/templates/error_401.json:/opt/tyk-gateway/templates/error_401.json
    depends_on:
      - tyk-redis
  tyk-gateway-2:
    image: tykio/tyk-gateway:${GATEWAY2_VERSION:-v3.1.2}
    ports:
      - 8081:8080
    networks:
      - tyk
    environment:
      - TYK_LOGLEVEL=${GATEWAY2_LOGLEVEL:-info}
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
      - TYK_GW_TRACER_ENABLED=${TRACING_ENABLED:-false}
    env_file:
    - .env
    volumes:
      - ./deployments/tyk/volumes/tyk-gateway/tyk-2.conf:/opt/tyk-gateway/tyk.conf
      - ./deployments/tyk/volumes/tyk-gateway/certs:/opt/tyk-gateway/certs
      - ./deployments/tyk/volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
    depends_on:
      - tyk-redis
      - tyk-gateway
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:${PUMP_VERSION:-v1.0.1}
    ports:
    - 8083:8083
    networks:
      - tyk
    volumes:
      - ./deployments/tyk/volumes/tyk-pump/pump.conf:/opt/tyk-pump/pump.conf
    environment:
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:?0}
      - TYK_LOGLEVEL=${PUMP_TYK_LOGLEVEL:-info}
    env_file:
    - .env
    depends_on:
      - tyk-redis
      - tyk-mongo
  tyk-redis:
    image: redis:6.0.4
    ports:
      - "6379:6379"
    volumes:
      - tyk-redis-data:/data
    networks:
      - tyk
  tyk-mongo:
    image: mongo:4.0
    command: ["mongod", "--smallfiles"]
    ports:
      - "27017:27017"
    volumes:
      - tyk-mongo-data:/data/db
    networks:
      - tyk
  httpbin:
    image: kennethreitz/httpbin:latest
    networks:
      tyk:
        aliases:
          - httpbin2
  swagger-petstore:
    image: swaggerapi/petstore:1.0.5
    networks:
      - tyk
    environment:
      - SWAGGER_HOST=http://swagger-petstore:8080
      - SWAGGER_URL=http://localhost:8080/swagger-petstore
  http-server:
    image: httpd:2.4.46-alpine
    networks:
      - tyk
    volumes:
      - ./deployments/tyk/volumes/http-server:/usr/local/apache2/htdocs
    ports:
      - "8888:80"

volumes:
  tyk-redis-data:
  tyk-mongo-data:

networks:
  tyk:
